package com.higyon.myapplication.appcomm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.lifecycle.bean.clocktime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLOCKTIME".
*/
public class clocktimeDao extends AbstractDao<clocktime, Long> {

    public static final String TABLENAME = "CLOCKTIME";

    /**
     * Properties of entity clocktime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property GetUptime = new Property(2, String.class, "getUptime", false, "GET_UPTIME");
        public final static Property Sleeptime = new Property(3, String.class, "sleeptime", false, "SLEEPTIME");
    }


    public clocktimeDao(DaoConfig config) {
        super(config);
    }
    
    public clocktimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLOCKTIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE\" TEXT," + // 1: date
                "\"GET_UPTIME\" TEXT," + // 2: getUptime
                "\"SLEEPTIME\" TEXT);"); // 3: sleeptime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLOCKTIME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, clocktime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String getUptime = entity.getGetUptime();
        if (getUptime != null) {
            stmt.bindString(3, getUptime);
        }
 
        String sleeptime = entity.getSleeptime();
        if (sleeptime != null) {
            stmt.bindString(4, sleeptime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, clocktime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String getUptime = entity.getGetUptime();
        if (getUptime != null) {
            stmt.bindString(3, getUptime);
        }
 
        String sleeptime = entity.getSleeptime();
        if (sleeptime != null) {
            stmt.bindString(4, sleeptime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public clocktime readEntity(Cursor cursor, int offset) {
        clocktime entity = new clocktime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // getUptime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // sleeptime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, clocktime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGetUptime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSleeptime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(clocktime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(clocktime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(clocktime entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
