package com.higyon.myapplication.appcomm.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lifecycle.bean.clocktime;
import com.example.lifecycle.bean.Location;
import com.example.lifecycle.bean.Step;
import com.example.lifecycle.bean.Time;

import com.higyon.myapplication.appcomm.greendao.clocktimeDao;
import com.higyon.myapplication.appcomm.greendao.LocationDao;
import com.higyon.myapplication.appcomm.greendao.StepDao;
import com.higyon.myapplication.appcomm.greendao.TimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clocktimeDaoConfig;
    private final DaoConfig locationDaoConfig;
    private final DaoConfig stepDaoConfig;
    private final DaoConfig timeDaoConfig;

    private final clocktimeDao clocktimeDao;
    private final LocationDao locationDao;
    private final StepDao stepDao;
    private final TimeDao timeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clocktimeDaoConfig = daoConfigMap.get(clocktimeDao.class).clone();
        clocktimeDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        stepDaoConfig = daoConfigMap.get(StepDao.class).clone();
        stepDaoConfig.initIdentityScope(type);

        timeDaoConfig = daoConfigMap.get(TimeDao.class).clone();
        timeDaoConfig.initIdentityScope(type);

        clocktimeDao = new clocktimeDao(clocktimeDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);
        stepDao = new StepDao(stepDaoConfig, this);
        timeDao = new TimeDao(timeDaoConfig, this);

        registerDao(clocktime.class, clocktimeDao);
        registerDao(Location.class, locationDao);
        registerDao(Step.class, stepDao);
        registerDao(Time.class, timeDao);
    }
    
    public void clear() {
        clocktimeDaoConfig.clearIdentityScope();
        locationDaoConfig.clearIdentityScope();
        stepDaoConfig.clearIdentityScope();
        timeDaoConfig.clearIdentityScope();
    }

    public clocktimeDao getClocktimeDao() {
        return clocktimeDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public StepDao getStepDao() {
        return stepDao;
    }

    public TimeDao getTimeDao() {
        return timeDao;
    }

}
